# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cvnf8V5AGa-XkwhT1qYDmGrfniEoq0-s
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Fitness_Classification.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# from sklearn import datasets
# from sklearn.tree import DecisionTreeClassifier
# 
# 
# st.write(''' # PREDICCION SOBRE LA CONDICIÓN FÍSICA DE UNA PERSONA  ''')
# st.image("ejercicio.jpeg", caption="Esta app esta disñeada para predecir si una persona estará en forma o no a partir de ciertos paramentros.")
# 
# st.header('Datos de evaluación')
# 
# def user_input_features():
#   # Entrada
#   age = st.number_input('EDAD:', min_value=1, max_value=100, value = 0, step = 1)
#   gender = st.number_input('GÉNERO(H=0, F=1):', min_value=0, max_value=1, value = 0, step = 1)
#   height_cm = st.number_input('ALTURA(cm):', min_value=1, max_value=300, value = 0, step = 1)
#   weight_kg = st.number_input('PESO(kg):',min_value=0, max_value=200, value = 0, step = 1)
#   heart_rate = st.number_input('RITMO CARDIACO (40-200):', min_value=40, max_value=200, value = 0, step = 1)
#   sleeep_hours = st.number_input('HORAS DE SUEÑO:', min_value = 0, max_value= 20, value= 0, step= 0)
#   activity_index = st.number_input('INDICE DE ACTIVIDAD(0-10)', min_value=0, max_value=10, value = 0, step = 1)
#   smokes = st.number_input("FUMA(NO = 0, SI =1)", min_value=0, max_value= 1, value=0, step=1)
# 
# 
#   user_input_data = {'EDAD:': age,
#                      'GÉNERO(H=0, F=1):': gender,
#                      'ALTURA(cm):': height_cm,
#                      'PESO(kg):': weight_kg,
#                      'RITMO CARDIACO (40-200):': heart_rate,
#                      'HORAS DE SUEÑO:': sleeep_hours,
#                      'INDICE DE ACTIVIDAD(0-10)': activity_index,
#                      'FUMA(NO = 0, SI =1)': smokes}
# 
#   features = pd.DataFrame(user_input_data, index=[0])
# 
#   return features
# 
# df = user_input_features()
# 
# titanic =  pd.read_csv('Fitness_Classification_Modificado.csv', encoding='latin-1')
# X = titanic.drop(columns='is_fit')
# Y = titanic['is_fit']
# 
# classifier = DecisionTreeClassifier(max_depth=3, criterion='entropy', min_samples_leaf=100, max_features=4, random_state=1615173)
# classifier.fit(X, Y)
# 
# prediction = classifier.predict(df)
# 
# st.subheader('Predicción')
# if prediction == 0:
#   st.write('NO ESTA EN FORMA')
# elif prediction == 1:
#   st.write('ESTA EN FORMA')
# else:
#   st.write('SIN PREDICCION')